import { FolderWithArticles } from '../components';
import { Article } from '@maas/core-api-models';

export const useMockData = () => {
  const mockFolders: FolderWithArticles[] = [
    {
      id: 'folder-1',
      issue: { id: 'issue-1', title: 'Issue #42' },
      name: 'Cover Stories',
      description: null,
      position: 0,
      color: '#3B82F6',
      cover: null,
      isPublished: true,
      articleCount: 3,
      articles: [
        {
          id: 'article-1',
          issue: { id: 'issue-1', title: 'Issue #42' },
          folder: { id: 'folder-1', name: 'Cover Stories' },
          title: 'The Future of AI in Healthcare',
          description: null,
          content: null,
          author: null,
          featuredImage: null,
          cover: null,
          pdf: null,
          keywords: null,
          type: 'feature',
          visibility: null,
          position: 0,
          publishedAt: null,
          isPublished: true,
          isFeatured: false,
          tags: null,
          viewCount: null,
          likeCount: null,
          categories: null,
        },
        {
          id: 'article-2',
          issue: { id: 'issue-1', title: 'Issue #42' },
          folder: { id: 'folder-1', name: 'Cover Stories' },
          title: 'Interview with Tech Leaders',
          description: null,
          content: null,
          author: null,
          featuredImage: null,
          cover: null,
          pdf: null,
          keywords: null,
          type: 'interview',
          visibility: null,
          position: 1,
          publishedAt: null,
          isPublished: true,
          isFeatured: false,
          tags: null,
          viewCount: null,
          likeCount: null,
          categories: null,
        },
        {
          id: 'article-3',
          issue: { id: 'issue-1', title: 'Issue #42' },
          folder: { id: 'folder-1', name: 'Cover Stories' },
          title: 'Breaking News Analysis',
          description: null,
          content: null,
          author: null,
          featuredImage: null,
          cover: null,
          pdf: null,
          keywords: null,
          type: 'news',
          visibility: null,
          position: 2,
          publishedAt: null,
          isPublished: false,
          isFeatured: false,
          tags: null,
          viewCount: null,
          likeCount: null,
          categories: null,
        },
      ],
    },
    {
      id: 'folder-2',
      issue: { id: 'issue-1', title: 'Issue #42' },
      name: 'Opinion',
      description: null,
      position: 1,
      color: '#10B981',
      cover: null,
      isPublished: true,
      articleCount: 3,
      articles: [
        {
          id: 'article-4',
          issue: { id: 'issue-1', title: 'Issue #42' },
          folder: { id: 'folder-2', name: 'Opinion' },
          title: 'Why We Need Better Regulations',
          description: null,
          content: null,
          author: null,
          featuredImage: null,
          cover: null,
          pdf: null,
          keywords: null,
          type: 'opinion',
          visibility: null,
          position: 0,
          publishedAt: null,
          isPublished: true,
          isFeatured: false,
          tags: null,
          viewCount: null,
          likeCount: null,
          categories: null,
        },
      ],
    },
  ];

  const mockStandaloneArticles: Article[] = [
    {
      id: 'article-9',
      issue: { id: 'issue-1', title: 'Issue #42' },
      folder: null,
      title: 'Quick Tips for Productivity',
      description: null,
      content: null,
      author: null,
      featuredImage: null,
      cover: null,
      pdf: null,
      keywords: null,
      type: 'tips',
      visibility: null,
      position: 0,
      publishedAt: null,
      isPublished: true,
      isFeatured: false,
      tags: null,
      viewCount: null,
      likeCount: null,
      categories: null,
    },
  ];
  return { mockFolders, mockStandaloneArticles };
};
